/* The BesselImp.c file,which implements the native function */
/* Java Native Interface headers */
#include <jni.h>
/* Autogenerated
header created by javah jni
*/
#include "Jniexams.h"
/* Include math.h for the prototype of function y0 */
#include <math.h>
JNIEXPORT jdouble JNICALL
Java_Jniexams_jniexams0(JNIEnv *env, jobject obj, jdouble x)
{
double y;
y = y0(x);
return y;
}