/* The Jniexams.h file generated from */
/* the Jniexams class by the javah tool. */
/* DO NOT EDIT THIS FILE it
is machine generated */
#include <jni.h>
/* Header for class Bessel */
#ifndef _Included_Jniexams
#define _Included_Jniexams
#ifdef __cplusplus
extern "C" {
#endif
/* Class: Jniexams
Method: jniexams0
Signature: (D)D */
JNIEXPORT jdouble JNICALL Java_Jniexams_jniexams0
(JNIEnv *, jobject, jdouble);
#ifdef __cplusplus
}
#endif
#endif